name: Your New Jekyll Site
markdown: redcarpet
pygments: true
url: http://192.168.1.79:9000
navigation:
- text: about
  url: /
- text: team
  url: /team/
- text: work
  url: /work/
- text: blog
  url: /blog/  
- text: contact
  url: /contact/  