name: Your New Jekyll Site
markdown: redcarpet
pygments: true
url: /actuatedfutures.com
navigation:
- text: about
  url: /
- text: team
  url: /team/
- text: work
  url: /work/
- text: news
  url: /news/  
- text: contact
  url: /contact/  
