name: Actuated Futures
markdown: redcarpet
pygments: true
url: ""
navigation:
- text: about
  url: /
- text: team
  url: /team/
- text: work
  url: /work/
- text: news
  url: /news/  
- text: contact
  url: /contact/  
